language: java
before_script:
    - sudo wget -q http://dl.google.com/android/android-sdk_r22.2.1-linux.tgz
    - sudo tar xzvf android-sdk_r22.2.1-linux.tgz > /dev/null
    - echo y | sudo android-sdk-linux/tools/android -s update sdk --filter android-18,platform-tools --no-ui
    - sudo android-sdk-linux/tools/android -s update project --path . --target "android-18"
    - sudo chmod -R 777 ./*

script:
    - ant clean
    - ant debug

